global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: false

entryPoints:
  web:
    address: ":8080"
  health:
    address: ":8082"

ping:
  entryPoint: health

tracing:
  serviceName: observability-demo-edge
  resourceAttributes:
    service.namespace: learning
    service.version: 3.7.8
    deployment.environment.name: local
  sampleRate: 1.0
  otlp:
    grpc:
      endpoint: otel-collector:4317
      insecure: true

metrics:
  otlp:
    serviceName: observability-demo-edge
    resourceAttributes:
      service.namespace: learning
      service.version: 3.7.8
      deployment.environment.name: local
    addEntryPointsLabels: true
    addRoutersLabels: false
    addServicesLabels: true
    pushInterval: 15s
    grpc:
      endpoint: otel-collector:4317
      insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

log:
  level: INFO
  format: json

accessLog:
  format: json
  fields:
    defaultMode: drop
    names:
      StartUTC: keep
      Duration: keep
      RouterName: keep
      ServiceName: keep
      RequestMethod: keep
      RequestProtocol: keep
      OriginStatus: keep
      DownstreamStatus: keep
      RetryAttempts: keep
    headers:
      defaultMode: drop
      names:
        X-Request-ID: keep
    queryParameters:
      defaultMode: drop
